### ISSUE TITLE
can't have no time

### ISSUE THREAD

**Issue by WilsontheWolf** [generalwrex/DiscordPresenceSetter#1]
you cannot set the timer to 0. You also can't have a count up.

**Comment by WilsontheWolf** [comment]
Creating Event Handlers...
Loaded Event Handlers
Discord Presence Setter Log 
Ready To Start!
Saving Current Settings...
Saved!
Initializing Discord RPC...
Initialized!
Sending Rich Presence Settings to Discord...
Sent!
Starting Callbacks...
Error    at System.Timers.Timer.set_Interval(Double value)
   at DiscordPresenceSetter.Form1.<.ctor>b__8_2(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by mnh48** [comment]
I have the same issue, the output is exactly the same as person above me.
